version: '3.3'
services:

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./db-data:/var/lib/posgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres